# Site
name: "Overthinking Analytically"
description: "Helping you decide the best in latest tech."
logo: "assets/images/cat.png"
favicon: "assets/images/favicon.ico"
baseurl: "https://ronynn.github.io"
disqus: # "demowebsite"
email: "analytical.overly@slmail.me"
mailchimp-list:

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-paginate
    - jekyll-seo-tag

authors:
    ronynn:
        name: Ronynn
        site: https://github.com/ronynn
        avatar: /assets/images/cat.jpg
        bio: "I'm Ronynn, a writer, game developer, and productivity enthusiast. I explore the intersections of technology, creativity, and self-improvement, sharing insights and strategies for optimal living."
        email: analytical.overly@slmail.me
        twitter: https://github.com/ronynn

# Defaults
defaults:
    # all posts
    - scope:
          path: "_posts"
      values:
          layout: post
          author: sal
          avatar: /assets/images/cat.jpg

    # all pages
    - scope:
          path: "_pages"
      values:
          layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 60

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
    [
        README.markdown,
        package.json,
        grunt.js,
        Gruntfile.js,
        Gruntfile.coffee,
        node_modules
    ]
